# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0006_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
