# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0007_newsarticle_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
